--------------------------------------------------------
--  File created - Saturday-December-16-2023   
--------------------------------------------------------
REM INSERTING into TB_ISSUE
SET DEFINE OFF;
Insert into TB_ISSUE (ID,APPLICATION_ID,PAGE_ID,TYPE,TITLE,ERROR_MESSAGE,DESCRIPTION,REPORTED_DATE,REPORTED_BY,ASSIGNED_TO,CREATED,CREATED_BY,UPDATED,UPDATED_BY,STATUS_ID) values (21,213,20,'Enhancement','Improve Look and Feel','N/A','Add visual elements.',to_date('30-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM','SANDRO@SOTFUL.COM',to_date('01-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('01-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',2);
Insert into TB_ISSUE (ID,APPLICATION_ID,PAGE_ID,TYPE,TITLE,ERROR_MESSAGE,DESCRIPTION,REPORTED_DATE,REPORTED_BY,ASSIGNED_TO,CREATED,CREATED_BY,UPDATED,UPDATED_BY,STATUS_ID) values (22,213,null,'Enhancement','Test Issue Here','N/A','Some description here.',to_date('01-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM','SANDRO@SOTFUL.COM',to_date('01-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('01-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',1);
Insert into TB_ISSUE (ID,APPLICATION_ID,PAGE_ID,TYPE,TITLE,ERROR_MESSAGE,DESCRIPTION,REPORTED_DATE,REPORTED_BY,ASSIGNED_TO,CREATED,CREATED_BY,UPDATED,UPDATED_BY,STATUS_ID) values (1,213,302,'Bug','Error When Logged In','Error 2221','Clicking on Login gives an error.',to_date('24-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM','SANDROGFERR',to_date('24-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('06-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',2);
REM INSERTING into TB_ISSUE_COMMENT
SET DEFINE OFF;
Insert into TB_ISSUE_COMMENT (ID,ISSUE_ID,COMMENT_TEXT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (1,1,'This is a comment.',to_date('15-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('15-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
Insert into TB_ISSUE_COMMENT (ID,ISSUE_ID,COMMENT_TEXT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2,1,'One more comment. Bla bla bla.',to_date('15-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('15-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
Insert into TB_ISSUE_COMMENT (ID,ISSUE_ID,COMMENT_TEXT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (42,1,'There are, of course, many ways to write down examples. We could write them on a board, on paper, or even as comments in a computer document. These are all reasonable and indeed, often, the best way to begin working on a problem.',to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
Insert into TB_ISSUE_COMMENT (ID,ISSUE_ID,COMMENT_TEXT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (43,1,'Whatever I want to write, I can write and send as a comment.',to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
Insert into TB_ISSUE_COMMENT (ID,ISSUE_ID,COMMENT_TEXT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (41,1,'This is another comment.',to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
REM INSERTING into TB_ISSUE_SCREENSHOT
SET DEFINE OFF;
Insert into TB_ISSUE_SCREENSHOT (ID,SCREENSHOT_FILENAME,SCREENSHOT_MIMETYPE,SCREENSHOT_CHARSET,SCREENSHOT_LASTUPD,CREATED,CREATED_BY,UPDATED,UPDATED_BY,ISSUE_ID) values (21,null,null,null,null,to_date('25-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('26-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',1);
REM INSERTING into TB_STATUS
SET DEFINE OFF;
Insert into TB_STATUS (ID,STATUS,CREATED,CREATED_BY,UPDATED,UPDATED_BY,SORT) values (1,'New',to_date('26-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('26-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',1);
Insert into TB_STATUS (ID,STATUS,CREATED,CREATED_BY,UPDATED,UPDATED_BY,SORT) values (2,'In Progress',to_date('26-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('26-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',2);
Insert into TB_STATUS (ID,STATUS,CREATED,CREATED_BY,UPDATED,UPDATED_BY,SORT) values (3,'Need Info',to_date('26-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',3);
Insert into TB_STATUS (ID,STATUS,CREATED,CREATED_BY,UPDATED,UPDATED_BY,SORT) values (4,'Ready to Test',to_date('26-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',4);
Insert into TB_STATUS (ID,STATUS,CREATED,CREATED_BY,UPDATED,UPDATED_BY,SORT) values (41,'Tested in TEST',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',6);
Insert into TB_STATUS (ID,STATUS,CREATED,CREATED_BY,UPDATED,UPDATED_BY,SORT) values (42,'Released to PROD',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',7);
Insert into TB_STATUS (ID,STATUS,CREATED,CREATED_BY,UPDATED,UPDATED_BY,SORT) values (5,'Tested in DEV',to_date('26-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',5);
REM INSERTING into TB_TEST
SET DEFINE OFF;
Insert into TB_TEST (ID,ISSUE_ID,TEST_DATE,TEST_BY,CREATED,CREATED_BY,UPDATED,UPDATED_BY,TEST_STATUS) values (41,1,null,'SANDRO@SOTFUL.COM',to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',1);
Insert into TB_TEST (ID,ISSUE_ID,TEST_DATE,TEST_BY,CREATED,CREATED_BY,UPDATED,UPDATED_BY,TEST_STATUS) values (26,1,to_date('15-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('15-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',5);
Insert into TB_TEST (ID,ISSUE_ID,TEST_DATE,TEST_BY,CREATED,CREATED_BY,UPDATED,UPDATED_BY,TEST_STATUS) values (42,1,to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('16-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',4);
REM INSERTING into TB_TEST_STATUS
SET DEFINE OFF;
Insert into TB_TEST_STATUS (ID,STATUS,SORT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (1,'In Progress',1,to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
Insert into TB_TEST_STATUS (ID,STATUS,SORT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2,'Error',2,to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
Insert into TB_TEST_STATUS (ID,STATUS,SORT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (5,'Approved',4,to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
Insert into TB_TEST_STATUS (ID,STATUS,SORT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (4,'Need Work',3,to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
REM INSERTING into TB_WORK
SET DEFINE OFF;
Insert into TB_WORK (ID,ISSUE_ID,WORK_START,WORK_END,WORK_BY,WORK_STATUS,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (1,1,to_date('28-NOV-23','DD-MON-RR'),to_date('30-NOV-23','DD-MON-RR'),'SANDRO@SOTFUL.COM','Done',to_date('01-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('01-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
REM INSERTING into TB_WORK_STATUS
SET DEFINE OFF;
Insert into TB_WORK_STATUS (ID,STATUS,SORT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (1,'In Progress',1,to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
Insert into TB_WORK_STATUS (ID,STATUS,SORT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (21,'Reassigned',4,to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
Insert into TB_WORK_STATUS (ID,STATUS,SORT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2,'Need Info',2,to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
Insert into TB_WORK_STATUS (ID,STATUS,SORT,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (3,'Ready to Test',3,to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM',to_date('14-DEC-23','DD-MON-RR'),'SANDRO@SOTFUL.COM');
