SELECT 
    APPLICATION_NAME,
    APPLICATION_ID 
FROM 
    APEX_APPLICATIONS;


DESC APEX_APPLICATION_PAGES   


SELECT 
    PAGE_NAME,
    PAGE_ID 
FROM 
    APEX_APPLICATION_PAGES;
    
SELECT * FROM APEX_APPLICATIONS;

DESC APEX_APPLICATIONS;




    
    
    
SELECT
    FIRST_NAME||' '||LAST_NAME||' - '||USER_NAME    NAME,
    USER_NAME,
    IS_ADMIN,
    IS_APPLICATION_DEVELOPER,
    ACCOUNT_LOCKED
FROM 
    APEX_WORKSPACE_APEX_USERS;

--Reported By
SELECT
    FIRST_NAME||' '||LAST_NAME||' - '||USER_NAME    NAME,
    USER_NAME
FROM 
    APEX_WORKSPACE_APEX_USERS;

--Assigned To
SELECT
    FIRST_NAME||' '||LAST_NAME||' - '||USER_NAME    NAME,
    USER_NAME
FROM 
    APEX_WORKSPACE_APEX_USERS
WHERE
    IS_APPLICATION_DEVELOPER = 'Yes';
    
    
    
SELECT
    I.ID,
    I.APPLICATION_ID,
    I.PAGE_ID,
    I.TYPE,
    I.TITLE,
    I.STATUS_ID,
    --(SELECT STATUS, MAX() WHERE ISSUE_ID = I.ID AND )
    I.ERROR_MESSAGE,
    I.DESCRIPTION,
    I.REPORTED_DATE,
    I.REPORTED_BY,
    I.ASSIGNED_TO,
    I.CREATED,
    I.CREATED_BY,
    I.UPDATED,p
    I.UPDATED_BY
FROM
    TB_ISSUE    I
    
    
    
SELECT 
    APPLICATION_NAME||' - '||APPLICATION_ID      APPLICATION,
    APPLICATION_ID 
FROM 
    APEX_APPLICATIONS;    
    
    
SELECT 
    PAGE_NAME||' - '||PAGE_ID    PAGE,
    PAGE_ID 
FROM 
    APEX_APPLICATION_PAGES;    